name: Release

on:
  push:
    tags:
      - cmd/protoc-gen-go-grpc/v[0-9]+.[0-9]+.[0-9]+

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download dependencies
        run: |
          cd cmd/protoc-gen-go-grpc
          go mod download

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
